In [1]:
import torch

# 设定初始参数

In [2]:
batch_size = 1
seq_len = 3  # 序列长度，可以理解为输入字符串长度
input_size = 4  # 输入大小，可以理解为向量的大小
hidden_size = 2  # 隐层大小

# 建立模型

In [4]:
cell = torch.nn.RNNCell(input_size=input_size, hidden_size=hidden_size)
# 注意这里调用的是RNNCell

# 初始化数据

In [3]:
# (seq, batch, features)
dataset = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(batch_size, hidden_size)

# 调用模型

In [5]:
for idx, input in enumerate(dataset):
    print('=' * 20, idx, '=' * 20)
    print('Input size: ', input_size)
    
    hidden = cell(input, hidden)
    
    print('outputs size: ', hidden_size)
    print(hidden)

==================== 0 ====================
Input size:  4
outputs size:  2
tensor([[0.4576, 0.9920]], grad_fn=<TanhBackward>)
==================== 1 ====================
Input size:  4
outputs size:  2
tensor([[0.5839, 0.4767]], grad_fn=<TanhBackward>)
==================== 2 ====================
Input size:  4
outputs size:  2
tensor([[-0.9072, -0.1955]], grad_fn=<TanhBackward>)
