### 5.4.1不带参数的层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self,X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
# 现在，我们可以将层作为组件合并到更复杂的模型中。
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [8]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(2.7940e-09, grad_fn=<MeanBackward0>)

### 5.4.2. 带参数的层

In [9]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):#表示输入数和输出数。
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [11]:
linear = MyLinear(5, 3)
linear.bias

Parameter containing:
tensor([-1.1519,  1.8713, -0.9645], requires_grad=True)

In [13]:
linear(torch.rand(2,5))

tensor([[0.0000, 1.0585, 0.0000],
        [0.0000, 0.8841, 0.0000]])

In [14]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [4.2105]])

### 5.4.3. 小结
- 我们可以通过基本层类设计自定义层。这允许我们定义灵活的新层，其行为与深度学习框架中的任何现有层不同。

- 在自定义层定义完成后，我们就可以在任意环境和网络架构中调用该自定义层。

- 层可以有局部参数，这些参数可以通过内置函数创建。